# Copyright (c) 2025 sw.consulting
# This file is a part of Media Pi backend

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mediapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./pgdata:/var/lib/mediapi/data

  api:
    image: ghcr.io/maxirmx/mediapi.core:latest
    ports:
      - "8085:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "https://+:8081;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/certificate/s.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password_File: "/certificate/s.pwd"
    volumes:
      - ./certificate:/certificate:ro

  ui:
    image: ghcr.io/maxirmx/mediapi.ui:latest
    ports:
      - "8082:8082"
      - "8083:8083"
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./certificate:/etc/nginx/certificate:ro
    environment:
      API_URL: https://mediapi.sw.consulting:8085/api

  backup:
    image: ghcr.io/sw-consulting/db-backup:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mediapi
      DB_USER: postgres
      DB_PASSWORD: postgres
      BACKUP_DIR: /backups
      RETENTION_DAYS: 7
    volumes:
      - ./backup/data:/backups
      - ./backup/logs:/var/log
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: always
    init: true
