# Copyright (C) 2025-2026 sw.consulting
# This file is a part of Media Pi backend

services:
  api:
    volumes:
      - certificate:/certificate:ro
      - storage:/var/lib/storage:rw

volumes:
  certificate:
  storage:
