# Copyright (c) 2025 sw.consulting
# This file is a part of Media Pi backend

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mediapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./pgdata:/var/lib/mediapi/data  #полный путь к корневому каталогу базы данных", на полный путь к корневому каталогу базы данных. Каталог создавать не надо, система создаст его при запуске.

  api:
    image: ghcr.io/sw-consulting/media-pi.core:latest
    ports:
      - "8084:8080"      #(B) Проброс порта API из Docker network в Host network
      - "8085:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "https://+:8081;http://+:8080"                          #(A) Проброс API из Docker network в Host network
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/certificate/s.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "<password>"       #Пароль к PKCS #12
    volumes:
      - R:/Projects/certificate:/certificate:ro               #Путь к сертификату на хосте", не забудьте указать полный путь к сертификату на хосте

  ui:
    image: ghcr.io/sw-consulting/media-pi.ui:latest
    ports:
      - "8082:8082"   #Проброс порта UI из Docker network в Host network      HTTP  (redirect на HTTPS)
      - "8083:8083"   #                                                        HTTPS   -- для доступа к интерфейсу необходимо использовать https://localhost:8083  (а не http://localhost:8082)   
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - R:/Projects/certificate:/etc/nginx/certificate:ro      #Путь к сертификату на хосте", не забудьте указать полный путь к сертификату на хосте
    environment:
      API_URL: https://localhost:8085/api                      #URL API из Host network (а не Docker network)   -- с (A) и (B)

  backup:
    image: ghcr.io/sw-consulting/db-backup:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mediapi
      DB_USER: postgres
      DB_PASSWORD: postgres
      BACKUP_DIR: /backups
      RETENTION_DAYS: 7
    volumes:
      - ./backup/data:/backups      #Полный путь к каталогу для резервных копий на хосте", не забудьте указать полный путь к каталогу для резервных копий на хосте. Каталог создастся при первом запуске.
      - ./backup/logs:/var/log      #полный путь к каталогу журналов резервного копирования", на полный путь к каталогу журналов резервного копирования. Каталог создавать не надо, система создаст его при запуске. 
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: always
    init: true
